let () =
	print_endline "Atom list:";
	print_endline (new Atom.hydrogen)#to_string;
	print_endline (new Atom.carbon)#to_string;
	print_endline (new Atom.oxygen)#to_string;
	print_endline (new Atom.calcium)#to_string;
	print_endline (new Atom.helium)#to_string;
	print_endline (new Atom.nitrogen)#to_string;
	print_endline (new Atom.magnesium)#to_string;
	print_endline (new Atom.uranium)#to_string;
	print_endline (new Atom.aluminum)#to_string;
	print_endline (new Atom.potassium)#to_string;
	print_endline (new Atom.sodium)#to_string;
	print_char '\n';
	print_endline "Molecule list :";
	print_endline (new Molecule.water)#to_string;
	print_endline (new Molecule.carbon_dioxyde)#to_string;
	print_endline (new Molecule.carbon_monoxyde)#to_string;
  	print_endline (new Molecule.aspirin)#to_string;
  	print_endline (new Molecule.caffeine)#to_string;
  	print_endline (new Molecule.trinitrotoluene)#to_string;
  	print_endline (string_of_bool ((new Molecule.water)#equals (new Molecule.water)));
  	print_endline (string_of_bool ((new Molecule.water)#equals (new Molecule.aspirin)));
  	print_char '\n';
  	print_endline "Alkane list :";
  	print_endline (new Alkane.alkane 1)#to_string;
  	print_endline (new Alkane.alkane 2)#to_string;
  	print_endline (new Alkane.alkane 8)#to_string;
  	print_endline (new Alkane.alkane 20)#to_string;
  	print_endline (new Alkane.alkane 14)#to_string;
  	print_endline (new Alkane.alkane 11)#to_string;
  	print_endline (new Alkane.alkane 7)#to_string;
  	print_endline (new Alkane.alkane 6)#to_string;
  	print_endline (new Alkane.alkane 9)#to_string;
  	print_endline (new Alkane.alkane 17)#to_string;
  	print_endline (new Alkane.alkane 4)#to_string;
  	print_endline (new Alkane.alkane 3)#to_string;
  	print_endline (new Alkane.alkane 12)#to_string;
  	print_endline (new Alkane.alkane 100)#to_string;